In [21]:
import numpy as np
arr_1d=np.array([1,2,3,4]) #create 1d array
print(arr_1d)

[1 2 3 4]


In [22]:
type(arr_1d) #check array yes and not

numpy.ndarray

In [23]:
arr_1d.ndim #checking 1d 2d and 3d array

1

In [24]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]]) #create 2d array
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
arr_2d.size #check total element in array

8

In [26]:
arr_2d.shape #check row and column in array

(2, 4)

In [27]:
arr_2d.dtype #check datatype in array int32, float64 etc

dtype('int64')

In [28]:
np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'