In [21]:
import numpy as np

In [22]:
mx_1s=np.ones(5) #create one in 5 time
print(mx_1s)

[1. 1. 1. 1. 1.]


In [23]:
mx_1s=np.ones((3,4))#create one in 3,4 shape
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
mx_1s=np.ones((3,4), dtype=int)#create one in 3,4 shape and change datatype
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [25]:
mx_1s=np.zeros((3,4))#create zero in 3,4 shape
print(mx_1s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
mx_1s=np.zeros((3,4), dtype=bool)#create zero in 3,4 shape and change datatype
print(mx_1s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [27]:
mx_1s=np.zeros((3,4), dtype=str)#create zero in 3,4 shape and change datatype
print(mx_1s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [28]:
mx_0s=""
print(bool(mx_0s))

False


In [29]:
mx_1s=np.empty((3,4)) #create empty array
print(mx_1s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
ar_id=np.arange(1,13) #create 1d array in 12 element
print(ar_id)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
ar_id=np.arange(1,13, 2) #create 1d array in 12 element in 2 gap
print(ar_id)

[ 1  3  5  7  9 11]


In [32]:
ar_id=np.linspace(1,25,5) #create 1d array in 5 element equaly different
print(ar_id)

[ 1.  7. 13. 19. 25.]


In [33]:
ar_id=np.arange(1,13).reshape(3,4) #create 1d array in 12 element and reshape(3,4) 3 row and 4 column
print(ar_id)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
ar_id.ravel() #convert 2d, 3d into 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
ar_id.flatten() #convert 2d, 3d into 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
ar_id.transpose() #convert row to column and column to row (3,4 to 4,3)
# ar_id.T same work ar_id.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])