In [3]:
import numpy as np
import random

In [8]:
np.random.random(3) #given three float value between 0 to 1

array([0.09509987, 0.61615163, 0.23432523])

In [10]:
np.random.random((3,3)) #given 3 row and 3 column float value between 0 to 1 

array([[0.19811725, 0.28460667, 0.68724901],
       [0.31430889, 0.65668156, 0.53407917],
       [0.7180335 , 0.47408818, 0.97897495]])

In [26]:
np.random.randint(1,10) #given one intger value between 1 to 9(1 included, 10 exclusive)

2

In [31]:
np.random.randint(1,10,(3,3)) #given 3 row and 3 column intger value between 1 to 9(1 included, 10 exclusive)

array([[4, 2, 3],
       [2, 2, 1],
       [4, 1, 1]])

In [35]:
np.random.seed(10) #seed return all time same value
np.random.randint(1,10,(3,3))

array([[5, 1, 2],
       [1, 2, 9],
       [1, 9, 7]])

In [36]:
np.random.rand(3) #given three float value between 0 to 1

array([0.68535982, 0.95339335, 0.00394827])

In [39]:
andom.random((3,3)) #given 3 row and 3 column float value between 0 to 1 

array([[0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412],
       [0.71457578, 0.54254437, 0.14217005]])

In [42]:
np.random.randn(3,3) #given 3 row and 3 column float value around -1,0, 1 

array([[ 1.484537  , -1.07980489, -1.97772828],
       [-1.7433723 ,  0.26607016,  2.38496733],
       [ 1.12369125,  1.67262221,  0.09914922]])

In [43]:
x=[1,2,3,4] #return 1 value in 1,2,3,4
np.random.choice(x)

1

In [49]:
# np.random.permutation(x) #return different-2 patern same suffle